#cors
cors:
  originPatterns: http://localhost:8080,http://localhost:3000
#JWT
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
#Spring doc
springdoc:
  pathsToMatch: /**/**
  swagger-ui:
    use-root-path: true
## PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teste
    username: postgres
    password: 12345